---

- name: Create container
  docker_container:
    name: "{{ docker_test_container_name }}"
    image: busybox
    command: "ping 127.0.0.1"
    pull: always
    detach: yes
    tty: yes
    memory_limit: 1024MB
    restart_policy: 'no'
    state: started
  failed_when: false # https://github.com/ansible/ansible-modules-core/issues/2611
  ignore_errors: yes # https://github.com/ansible/ansible-modules-core/issues/2611

- name: Remove container
  docker_container:
    name: "{{ docker_test_container_name }}"
    image: busybox
    state: absent
